[2021-12-31 00:37:03,069] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2021-12-27T09:00:00+00:00 [queued]>
[2021-12-31 00:37:03,084] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2021-12-27T09:00:00+00:00 [queued]>
[2021-12-31 00:37:03,084] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 00:37:03,084] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-12-31 00:37:03,084] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 00:37:03,092] {taskinstance.py:901} INFO - Executing <Task(TwitterOperator): twitter_aluraonline> on 2021-12-27T09:00:00+00:00
[2021-12-31 00:37:03,095] {standard_task_runner.py:54} INFO - Started process 15437 to run task
[2021-12-31 00:37:03,176] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'twitter_dag', 'twitter_aluraonline', '2021-12-27T09:00:00+00:00', '--job_id', '38', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/twitter_dag.py', '--cfg_path', '/var/folders/yv/xtbkkbn565j6hhnrh5chcn4r0000gn/T/tmp1s7sv7as']
[2021-12-31 00:37:03,178] {standard_task_runner.py:78} INFO - Job 38: Subtask twitter_aluraonline
[2021-12-31 00:37:08,225] {logging_mixin.py:112} INFO - Running <TaskInstance: twitter_dag.twitter_aluraonline 2021-12-27T09:00:00+00:00 [running]> on host MacBook-Pro-de-Roberto.local
[2021-12-31 00:37:13,335] {base_hook.py:89} INFO - Using connection to: id: twitter_default. Host: https://api.twitter.com, Port: None, Schema: None, Login: None, Password: None, extra: XXXXXXXX
[2021-12-31 00:37:13,338] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2021-12-27T09:00:00.00Z&end_time=2021-12-28T09:00:00.00Z
[2021-12-31 00:37:15,598] {logging_mixin.py:112} WARNING - /Users/roberto-almeida/datapipeline/.env/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.twitter.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
[2021-12-31 00:37:15,887] {logging_mixin.py:112} INFO - /Users/roberto-almeida/datapipeline/datalake/bronze/twitter_aluraonline/extract_date=2021-12-27/AluraOnline_20211227.json
[2021-12-31 00:37:15,889] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2021-12-27T09:00:00.00Z&end_time=2021-12-28T09:00:00.00Z&next_token=b26v89c19zqg8o3fpe17g6tpvxcqruka7x39j94jo3eyl
[2021-12-31 00:37:15,891] {logging_mixin.py:112} WARNING - /Users/roberto-almeida/datapipeline/.env/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.twitter.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
[2021-12-31 00:37:16,152] {logging_mixin.py:112} INFO - /Users/roberto-almeida/datapipeline/datalake/bronze/twitter_aluraonline/extract_date=2021-12-27/AluraOnline_20211227.json
[2021-12-31 00:37:16,155] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2021-12-27T09:00:00.00Z&end_time=2021-12-28T09:00:00.00Z&next_token=b26v89c19zqg8o3fpe17g4odv3fir25atbdidx9rv6hdp
[2021-12-31 00:37:16,157] {logging_mixin.py:112} WARNING - /Users/roberto-almeida/datapipeline/.env/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.twitter.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
[2021-12-31 00:37:16,639] {logging_mixin.py:112} INFO - /Users/roberto-almeida/datapipeline/datalake/bronze/twitter_aluraonline/extract_date=2021-12-27/AluraOnline_20211227.json
[2021-12-31 00:37:16,654] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=twitter_dag, task_id=twitter_aluraonline, execution_date=20211227T090000, start_date=20211231T033703, end_date=20211231T033716
[2021-12-31 00:37:18,176] {local_task_job.py:102} INFO - Task exited with return code 0
